""" images for tournaments

Revision ID: 38725b421c87
Revises: 42e6a5bb3e2d
Create Date: 2024-06-13 23:09:33.920454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38725b421c87'
down_revision: Union[str, None] = '42e6a5bb3e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('images', sa.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'images')
    # ### end Alembic commands ###