"""auth table and tournament

Revision ID: 693d9a068d1d
Revises: e795c3ec4bb4
Create Date: 2024-05-08 22:07:05.609851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693d9a068d1d'
down_revision: Union[str, None] = 'e795c3ec4bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_data_id', table_name='auth_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_data_id', 'auth_data', ['id'], unique=False)
    # ### end Alembic commands ###
