"""Add particpant model

Revision ID: 7825fd04273a
Revises: 38725b421c87
Create Date: 2024-06-19 23:30:07.455616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7825fd04273a'
down_revision: Union[str, None] = '38725b421c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('tournaments_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('organized_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'participant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###