"""remove_user_manager

Revision ID: e7e66431defd
Revises: 7825fd04273a
Create Date: 2024-06-21 16:48:35.130493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7e66431defd'
down_revision: Union[str, None] = '7825fd04273a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('past_tournaments', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('current_tournaments', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('futur_tournaments', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('organizer_tournaments', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###