"""Create a baseline migrations

Revision ID: f5bd34fa410a
Revises: 
Create Date: 2024-04-29 22:06:05.632586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bd34fa410a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.add_column('tournaments', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tournaments', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('tournaments', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tournaments', 'start_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('tournaments', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tournaments', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tournaments', 'organizer_id')
    op.drop_column('tournaments', 'description')
    op.drop_column('tournaments', 'end_date')
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clients_pkey')
    )
    # ### end Alembic commands ###
